CREATE TABLE dim_notification_types (
    notification_type_id SERIAL PRIMARY KEY,
    type_name VARCHAR(50) UNIQUE NOT NULL,
    category VARCHAR(50) NOT NULL,
    is_system_generated BOOLEAN DEFAULT FALSE,
    description TEXT
);

CREATE INDEX idx_notification_types_category ON dim_notification_types(category);

COMMENT ON TABLE dim_notification_types IS 'Dimension table for different categories and types of in-game notifications and messages.';
COMMENT ON COLUMN dim_notification_types.notification_type_id IS 'Unique identifier for the notification type (Primary Key).';
COMMENT ON COLUMN dim_notification_types.type_name IS 'The specific name of the notification type (e.g., "System Welcome", "Private Message", "Platoon Invite").';
COMMENT ON COLUMN dim_notification_types.category IS 'Broad category of the notification (e.g., "System", "Private", "Clan", "Event").';
COMMENT ON COLUMN dim_notification_types.is_system_generated IS 'Flag indicating if the notification is automatically generated by the game system.';
COMMENT ON COLUMN dim_notification_types.description IS 'A more detailed description of the notification type.';